"""add phone number

Revision ID: 35823250974b
Revises: faf2221eb807
Create Date: 2023-06-06 17:38:13.750964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35823250974b'
down_revision = 'faf2221eb807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
